name: Publish Python Package

on:
  push:
    branches:
      - main  # Runs on push to the main branch
    paths:
      - "setup.py"  # Only trigger when 'setup.py' is changed
    # paths-ignore:
    #   - "**/*.md"  # Ignore Markdown files
    #   - "**/*.txt"  # Ignore text files
    #   - "**/*"      # Ignore any other files except 'setup.py'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    outputs:
      package_version: ${{ env.PACKAGE_VERSION }}  # Pass version to next job

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine

      - name: Extract version from setup.py
        id: get_version
        run: |
          VERSION=$(python extract_version.py)
          echo "PACKAGE_VERSION=$VERSION" >> $GITHUB_ENV  # Use environment file
          echo "Extracted version: $VERSION"

      - name: Build the package
        run: |
          python setup.py sdist bdist_wheel

      - name: Verify built files
        run: |
          echo "Built package files:"
          ls -lh dist/

      - name: Upload built package as artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-package-${{ env.PACKAGE_VERSION }}
          path: dist/
          compression-level: 0  # Faster upload

  publish:
    needs: build-and-publish
    runs-on: ubuntu-latest
    env:
      PACKAGE_VERSION: ${{ needs.build-and-publish.outputs.package_version }}  # Retrieve version from previous job

    steps:
      - name: Download built package artifact
        uses: actions/download-artifact@v4
        with:
          name: python-package-${{ env.PACKAGE_VERSION }}
          path: dist/

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install Twine
        run: |
          python -m pip install --upgrade pip
          pip install twine

      - name: Upload package to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          echo "Uploading package version $PACKAGE_VERSION from extracted artifact..."
          twine upload dist/*
